# please keep this file alphabetically ordered!

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'frontend/**/*'
    - 'build/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'Gemfile'
  DisplayStyleGuide: true
  DisplayCopNames: true

Layout/AlignParameters:
  Enabled: false

Layout/CaseIndentation:
  IndentOneStep: true

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousOperator:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'spec/**/*'

Lint/BooleanSymbol:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 250

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/**/*'

Performance/RedundantMatch:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: false

Rails/Delegate:
  EnforceForPrefixed: false

Rails/FilePath:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/OutputSafety:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - 'app/views/**/*.jbuilder'

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Naming/PredicateName:
  NamePrefix:
    - is_
  NamePrefixBlacklist:
    - is_

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/YodaCondition:
  Enabled: false
