version: '2'

services:
  db:
    image: 'postgres:9.5'
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
  app:
    depends_on:
      - 'db'
    build: .
    ports:
      - '3000:3000'
    env_file: '.env'

volumes:
  db:
