name: CI

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2']
    services:
      postgres:
        image: postgres:11.0
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: test_track_test
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Prepare DB
        run: bundle exec rake db:test:prepare
      - name: Precompile assets
        run: bundle exec rake assets:precompile
      - name: Run tests
        run: bundle exec rake
        env:
          CAPYBARA_DRIVER: better_cuprite
          COMPILE_ASSETS: 0
          EAGER_LOAD: 1
